[package]
name = "nu_plugin_semver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nu-plugin = "0.88.1"
nu-protocol = "0.88.1"
semver = { version = "1.0.20", features = ["serde"] }
serde = "1"
typetag = "0.2"
